paradigmxyz/cryo

README.md
```
➜  cryo git:(main) cargo install --path .
error: found a virtual manifest at `/Users/erikreppel/dev/cryo/Cargo.toml` instead of a package manifest
```
Install command in README fails
Install the cli directly
```
➜  cryo git:(main) cargo install --path ./crates/cli 
Installing cryo_cli v0.1.0 (/Users/erikreppel/dev/cryo/crates/cli)
Updating crates.io index
Downloaded byte-slice-cast v1.2.2
Downloaded phf_macros v0.11.2
Downloaded bytemuck v1.13.1
...
Installing /Users/erikreppel/.cargo/bin/cryo
Installed package `cryo_cli v0.1.0 (/Users/erikreppel/dev/cryo/crates/cli)` (executable `cryo`)
➜  cryo git:(main) cryo
error: the following required arguments were not provided:
<DATATYPE>...
Usage: cryo <DATATYPE>...
For more information, try '--help'.
```
-   [ ] Added …
=> Fix install command in docs

crates/freeze/src/datasets/traces.rs, crates/freeze/src/types/errors.rs
Rather than assuming a rate limit error, return the error message from the RPC node
This far from perfect as it doesn't account for other error cases. Ideally we could pattern match to find the exact error case but different RPC providers return diff error formats. But I think this is potentially more helpful when debugging dataset requests
ex.
Alchemy
RETH with traces disabled
Before this PR:
TODOs
=> Surface RPC error in trace

crates/freeze/src/types/errors.rs
Errors are often very opaque, e.g. "Parse error" even when there was specific IO or logic error causing it underneath.
Make some of the errors `transparent` or include inner error message in the final error
-   [none] Breaking changes
=> Better error propagation / display.

crates/cli/src/main.rs
When some chunk collection fails the `cryo` command happily returns success code and tooling can't notice failures
Return `Err` from main when some chunk failed
-   [not applicable ] Added Tests
-   [not applicable ] Added Documentation
-   [command previously succeeded when there were errors, now it's not ] Breaking changes
=> Return error from main when some chunks failed.

crates/cli/src/parse/file_output.rs, crates/cli/src/summaries.rs, crates/freeze/src/types/chunks/chunk.rs, crates/freeze/src/types/chunks/chunk_ops.rs, crates/freeze/src/types/dataframes/export.rs, crates/freeze/src/types/files.rs, crates/freeze/src/types/queries.rs, crates/freeze/src/types/summaries.rs, crates/python/src/freeze_adapter.rs
Use of strings for operating on paths is error prone and more verbose
Use `std::path::Path` and `std::path::PathBuf` for output paths processing
-   [refactor] Added Tests
-   [no new code] Added Documentation
-   [none] Breaking changes
=> Use Path instead of String for output dir.

crates/freeze/src/datasets/blocks.rs, crates/freeze/src/datasets/logs.rs, crates/freeze/src/datasets/transactions.rs
Create `LogsColumns`.
Refactor transaction columns to transaction's file.
Move column data collection code into functions of respective structs.
-   [ none ] Breaking changes
=> refactor: cleanup collecting and managing column data

crates/freeze/src/datasets/transactions.rs, crates/freeze/src/types/dataframes/creation.rs
Fixes https://github.com/paradigmxyz/cryo/issues/55
Since `column_type` returns `U256` now, the check for hex should be against the global column encoding instead of column type.
-   [ none ] Breaking changes
=> fix(u256) hex output check for u256 series generation.

crates/cli/src/parse/args.rs, crates/cli/src/parse/blocks.rs, crates/cli/src/parse/query.rs, crates/cli/src/parse/source.rs, crates/freeze/src/datasets/blocks.rs, crates/freeze/src/datasets/blocks_and_transactions.rs, crates/freeze/src/datasets/contracts.rs, crates/freeze/src/datasets/logs.rs, crates/freeze/src/datasets/native_transfers.rs, crates/freeze/src/datasets/state_diffs.rs, crates/freeze/src/datasets/traces.rs, crates/freeze/src/datasets/transactions.rs, crates/freeze/src/types/mod.rs, crates/freeze/src/types/sources.rs
Right now semaphore and rate-limiting code is spread and duplicated all over the code-base, some calls to rpc methods are actually missing them.
Create a wrapper for `Provider` that centralized all rpc accesses and makes sure concurrency controls are applied to all of them.
In future this might also allow easy introduction of re-tries in presence of network or transient target endpoint errors.
It's probably possible to make `Fetcher` implement `Middleware` trait and maybe reduce a bit some of the function signature changes, but at the moment this seemed easier and ensures all used rpc methods properly follows concurrency checks without overriding *all* middleware functions. 
-   [ adjusted existing test ] Added Tests
-   [ x ] Added Documentation
-   [ none ] Breaking changes
=> refactor(source): extract concurrency checks and rpc fetches into separate `Fetcher` struct

README.md, crates/freeze/src/datasets/transactions.rs, crates/freeze/src/types/sources.rs
resolves #93
To add a robust fallback mechanism for `eth_getBlockReceipts`, which had become outdated after recent updates, I created an extension trait `FetcherExt`. This trait is implemented for `Arc<Fetcher<P>>` and allows us to use reference of rate-limited providers over multiple tasks. I welcome any feedback on how to test this implementation effectively.
command tested:
```
$ cryo txs -b 145968168:145968169 --rpc https://arb1.arbitrum.io/rpc
```
before:
```
...
collecting data
───────────────
started at 2023-11-01 15:54:01.276
done at 2023-11-01 15:54:01.639
error summary
─────────────
(errors in 1 chunks)
- Failed to get block: (code: -32601, message: the method eth_getBlockReceipts does not exist/is not available, data: None) (1x)
collection summary
──────────────────
- total …
```
=> fallback to multiple `eth_getTransactionReceipt` calls if `eth_getBlockReceipts` is not present

crates/freeze/src/datasets/transactions.rs, crates/freeze/src/multi_datasets/blocks_and_transactions.rs
I would like to propose optional columns to transactions to include block_timestamp and block_hash. In some cases it is good to have this information directly in the transactions and not to have to link it from the blocks.
I have added default columns to transactions to be the original field set and extended the CollectByBlock and CollectByTransaction implementations for BlocksAndTransactions and Transactions.
Please let me know if I should extend some tests, I haven't found any related to that part of code or maybe I missed something.
-   [ ] Breaking changes
=> Add block_timestamp, block_hash as optional columns to transactions

crates/cli/src/main.rs
Looks like the comments are swapped.
[cfg(not(debug_assertions))] is for release builds, and [cfg(debug_assertions)] for debug builds.
=> Fix typo in error handling comment

crates/freeze/src/types/chunks/number_chunk.rs, crates/freeze/src/types/chunks/subchunks.rs
`NumberChunk` had a method named `numbers()` that had a comment mentioning it was to be replaced by `values()`.
I replaced the remaining usage of `numbers()` with `values()` and deleted `numbers()`.
For testing, I ran a `cryo log` command for for a given address for a certain range of blocks and checked that the output contained all the logs seen for that address on etherscan, along with a temporary print statement (not in the commit) used to print out all the block numbers in `block_numbers` in `parse_partitions`.
=> refactor: remove NumberChunk's numbers() function

crates/freeze/src/datasets/erc20_transfers.rs, crates/freeze/src/datasets/erc721_transfers.rs, crates/freeze/src/datasets/native_transfers.rs, crates/freeze/src/datasets/traces.rs
Solves #97.
For traces, take from/to according to appropriate trace type and compare with given parameters. For ERC transfers, compare appropriate indexed log with given parameters.
-   [ ] Breaking changes
=> filter erc transfers and traces by from/to addresses

README.md
As of the test case below, the starting and block number range for the case when we have a minus on the start should be incremented by 1
Also a typo in the unit for the case when "plus sign on end means plus start"
=> docs: fix typo in block number ranges

crates/cli/src/parse/query.rs, crates/cli/src/parse/schemas.rs, crates/freeze/src/types/chunks/subchunks.rs
The primary goal of these changes is to enhance the readability and efficiency of the code in the `Args` struct. In its previous state, certain functions like `dim_is_none` and `parse_u256_types` were more verbose than necessary and did not fully leverage Rust's expressive capabilities. By refactoring these functions, we aim to make the codebase cleaner, more maintainable, and easier for other contributors to understand and work with.
1. `DimIsNone` Trait Refactoring:
- Simplified the `dim_is_none` function by returning the negation of `dim_is_some`, thereby removing redundant match statements.
2. `parse_u256_types` Function Optimization:
- Refactored to use `map_or` and `map` for more idiomatic and streamlined logic.
- Consolidated string comparisons in pattern matching to improve …
=> refactor: streamlining `DimIsNone` trait and optimizing `parse_u256_types`

Cargo.lock, Cargo.toml
polars 0.35.4 faces [this issue](https://github.com/pola-rs/polars/issues/12938) when running `cargo build`
update polars to 0.36.2
-   [x] Added Tests
-   [x] Added Documentation
-   [x] Breaking changes
=> chore: update polars to 0.36.2

.github/workflows/build_and_test.yml, Cargo.lock
Currently building cryo on nightly fails because of old locked dependencies. Running `cargo update` fixes this.
Additionally I updated CI to use the latest action and Rust versions, and to add caching.
=> chore: fix nightly, update CI jobs

README.md, crates/freeze/src/datasets/erc20_approvals.rs, crates/freeze/src/datasets/mod.rs, crates/freeze/src/types/datatypes/scalar.rs, crates/freeze/src/types/signatures.rs
Add `erc20_approvals` datasets, which is very samiliar to `erc20_transfers` but replace the event `topic0`.
-   [ ] Breaking changes
=> Add erc20_approvals datasets

README.md
**Description**:  
This pull request fixes two typos found in the documentation that could cause confusion or appear unprofessional to readers:  
1. **"Python Instalation" heading**  
- **Error**: *Instalation*  
- **Correction**: *Installation*  
- **Importance**: This is a prominent section header, and such errors may reduce the credibility of the documentation. Correct spelling ensures a polished and professional presentation.
2. **"Documenation" in the Table of Contents**  
- **Error**: *Documenation*  
- **Correction**: *Documentation*  
- **Importance**: The Table of Contents is a crucial navigational aid. Typographical errors in it may confuse users and create inconsistency with the linked section headings. This fix ensures better user experience and clarity.
Both fixes contribute …
=> Fix typos Update README.md

crates/freeze/src/types/sources.rs
fixes parameter name in a comment for `get_block_by_hash` in `sources.rs`
=> fix param name in comment

examples/uniswap.sh
1. **Corrected spelling of "interuptable":**  
- **Original:** "interuptable: you can interrupt the script whenever you want, the data will be fine"  
- **Corrected:** "interruptible: you can interrupt the script whenever you want, the data will be fine"  
- **Reason:** "Interuptable" is a misspelling. The correct word is "interruptible," ensuring clarity and grammatical accuracy.  
2. **Corrected spelling of "re-runing":**  
- **Original:** "re-runing the script does not re-collect data"  
- **Corrected:** "re-running the script does not re-collect data"  
- **Reason:** "Re-runing" is a misspelling. The correct word is "re-running," which accurately conveys the intended meaning.  
Clear and error-free comments are crucial for maintaining the readability and professionalism of the …
=> Typos Update uniswap.sh

.gitignore, crates/cli/src/run.rs
This PR was motivated by my attempts to understand the file. It only touches the `run.rs` file and tries to improve it with better structuring, more descriptive function names, and modularized code. The code behavior doesn't change with this PR.
It reduces the `run` function by breaking down its complex logic into smaller, well-defined, and descriptive functions, with the goal of improving readability and maintainability. 
It adds `.env` files to gitignore, allowing users to source env. variables only in the context of the terminal.
-   [X] Added Tests
-   [ ] Breaking changes
=> Improved run.rs

crates/cli/src/remember.rs
Corrected `rememebered` to `remembered`
=> fix: typos in documentation files

.github/PULL_REQUEST_TEMPLATE.md, crates/freeze/src/types/files.rs
Detailed Changes:
1. crates/freeze/src/types/files.rs:
- /// File format to used for output files
+ /// File format to use for output files
Reason: Fixed grammatical error. The phrase "to used" is incorrect English grammar. The correct form is "to use" when describing the purpose of the file format.
2. .github/PULL_REQUEST_TEMPLATE.md:
- Contributors guide: https://github.com/paradigmxyz/flood/blob/master/CONTRIBUTING.md
+ Contributors guide: https://github.com/paradigmxyz/cryo/blob/master/CONTRIBUTING.md
Reason: Fixed incorrect repository link. The link was pointing to a non-existent "flood" repository instead of the correct "cryo" repository. This ensures contributors are directed to the correct contributing guidelines.
PR Checklist
[x] Added Documentation Updates
[ ] Added Tests (not …
=> Fix Documentation Typos and Links

crates/freeze/src/types/execution.rs
Reason:
Using `Self::default()` makes the code more readable and understandable. It explicitly indicates the call to the `default` method for the current type (`Self`), which simplifies code comprehension, especially for developers familiar with the `Default` pattern.
`..Default::default()` adds redundancy since the `ExecutionEnvBuilder` object is already returned through the `default()` call. This simplification improves code readability and maintainability.
=> Improve Code Readability by Replacing ..Default::default() with Self::default()
